github: [metadata]
kramdown:
    input: GFM
    hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
lsi: false
safe: true
source: [your repo's top level directory]
   incremental: false
   highlighter: rouge
gist:
   noscript: false

