# Jekyll Defaults
title: Little Big Blue
description: A small and simple site I made to test out Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog

url: "http://localhost:3000"
github: http://github.com/ITSJOHNCENA

markdown: redcarpet
highlighter: rouge
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: feed.xml
tags_path: tag.html
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
